export { default as Tab1 } from './tab1'
export { default as Tab2 } from './tab2'
export { default as Tab3 } from './tab3'
export { default as Tab4 } from './tab4'
export { default as Tab5 } from './tab5'
export { default as Tab6 } from './tab6'
export { default as Tab7 } from './tab7'
export { default as Tab8 } from './tab8'