<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CategorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            [
                'id'         => 1,
                'title'      => 'All Posts',
                'slug'       => 'all-posts',
                'logo'       => null,
                'desc'       => null,
                'type'       => 'post',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'         => 2,
                'title'      => 'Exhibition Stand Design',
                'slug'       => 'exhibition-stand-design',
                'logo'       => null,
                'desc'       => null,
                'type'       => 'post',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'         => 3,
                'title'      => 'Exhibition Stand Trends',
                'slug'       => 'exhibition-stand-trends',
                'logo'       => null,
                'desc'       => null,
                'type'       => 'post',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'         => 4,
                'title'      => 'Project Management',
                'slug'       => 'project-management',
                'logo'       => null,
                'desc'       => null,
                'type'       => 'post',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'         => 5,
                'title'      => 'All Stands',
                'slug'       => 'all-stands',
                'logo'       => '/',
                'desc'       => null,
                'type'       => 'event_cat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'         => 6,
                'title'      => 'SiGMA Malta',
                'slug'       => 'sigma-malta',
                'logo'       => '/',
                'desc'       => null,
                'type'       => 'event_cat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'         => 7,
                'title'      => 'Interlift Germany',
                'slug'       => 'interlift-germany',
                'logo'       => '/',
                'desc'       => null,
                'type'       => 'event_cat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'         => 8,
                'title'      => 'ICE London',
                'slug'       => 'ice-london',
                'logo'       => '/',
                'desc'       => null,
                'type'       => 'event_cat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'         => 9,
                'title'      => 'iGB Amsterdam',
                'slug'       => 'igb-amsterdam',
                'logo'       => '/',
                'desc'       => null,
                'type'       => 'event_cat',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'         => 10,
                'title'      => '2019',
                'slug'       => '2019',
                'logo'       => null,
                'desc'       => 'Step into 2019\'s captivating world. Explore our stunning exhibition stands, crafted with creativity and precision.',
                'type'       => 'event_year',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'         => 11,
                'title'      => '2021',
                'slug'       => '2021',
                'logo'       => null,
                'desc'       => 'Step into 2021\'s captivating world. Explore our stunning exhibition stands, crafted with creativity and precision.',
                'type'       => 'event_year',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'         => 12,
                'title'      => '2022',
                'slug'       => '2022',
                'logo'       => null,
                'desc'       => 'Step into 2022\'s captivating world. Explore our stunning exhibition stands, crafted with creativity and precision.',
                'type'       => 'event_year',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'         => 13,
                'title'      => '2023',
                'slug'       => '2023',
                'logo'       => null,
                'desc'       => 'Step into 2023\'s captivating world. Explore our stunning exhibition stands, crafted with creativity and precision.',
                'type'       => 'event_year',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'         => 14,
                'title'      => '5x5',
                'logo'       => null,
                'slug'       => '5x5',
                'desc'       => null,
                'type'       => 'stand_size',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'         => 15,
                'title'      => '7x11',
                'logo'       => null,
                'slug'       => '7x11',
                'desc'       => null,
                'type'       => 'stand_size',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'         => 16,
                'title'      => '4.5x7',
                'logo'       => null,
                'slug'       => '4.5x7',
                'desc'       => null,
                'type'       => 'stand_size',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'         => 17,
                'title'      => '3x5',
                'logo'       => null,
                'slug'       => '3x5',
                'desc'       => null,
                'type'       => 'stand_size',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'         => 18,
                'title'      => '3.5x6',
                'logo'       => null,
                'slug'       => '3.5x6',
                'desc'       => null,
                'type'       => 'stand_size',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'         => 19,
                'title'      => '3x6',
                'logo'       => null,
                'slug'       => '3x6',
                'desc'       => null,
                'type'       => 'stand_size',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('categories')->insert($data);
    }
}
